### ISSUE TITLE
Bot Spawning

### ISSUE THREAD

**Issue by BlackFranky** [JoeStrout/Farmtronics#11]
By pressing the Page Up button a bot is spawned two tiles left to the player. 
This may be intended but it is an issue because:
1. I use the Page Up button to navigate in programs inside the bot or pc. I know you can use Ctrl+U, but I am used to using Page Up and often do that unconsiously.
2. It spawns even if the tile is already occupied or inaccessible.
3. Interacting with this spawned bot sometimes freezes the game resulting in a game crash. The only save way to interact is destroying and deleting it.

**Comment by JoeStrout** [comment]
Fixed in release 1.0.8.
