### ISSUE TITLE
Coop and Greenhouse are not reported in tile info

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/Farmtronics#16]
`farm.tile` on any position containing this buildings just reports `null`.

**Comment by JoeStrout** [comment]
(May apply to other constructed buildings too.)

**Comment by JoeStrout** [comment]
(Greenhouse ruins may suffice for testing this.)

**Comment by greysondn** [comment]
The most recent version of the mod seems (on its face) to resolve this.

Advise "close - fixed" and listen for people to still complain about specific structures being missed by the implementation.

Source: I did the testing; it's in JoeStrout's [Miniscript Discord Server](https://discord.gg/7s6zajx) logs [here](https://discord.com/channels/646000428441534474/910679364335730718/984999921868476466).

**Comment by JoeStrout** [comment]
Agreed.
