### ISSUE TITLE
Feature request: Read from/write to in-game chat

### ISSUE THREAD

**Issue by greysondn** [JoeStrout/Farmtronics#18]
This request is very label-on-the-tin type.

I first briefly mentioned this in JoeStrout's [MiniScript Discord server](https://discord.gg/7s6zajx); it can be found in the logs [here](https://discord.com/channels/646000428441534474/910679364335730718/987732490787635250). That request has been split into two requests, however, as it seems to be asking for two very different things in the underlying game as far as I can tell.

Detailed Description
----------------------
The game provides an in-game chat for players that can be used to run server commands and talk to one another. Messages in the chat provide a log accessible to the player.  (I am aware that Farmtronics doesn't presently support multiplayer; it's of note that this chat is able to be accessed even in a single-player session. Default key map appears to be `t`.)

What I'm proposing is that the MiniScript interpreter in Farmtronics needs to be able to read from and write to this interface element.

Here's some snapshots of it open at the bottom of the screen on a modded version of the game.

![image](https://user-images.githubusercontent.com/3652901/175161361-d4052e73-0548-4fa1-98d9-9ef433a0a692.png)

![image](https://user-images.githubusercontent.com/3652901/175161496-caf83de2-8ad4-4d0e-b5b1-b0c6a0688ca7.png)

Usecase or Problem Being Solved
-------------------------------------
There are two main uses for this, which can be separated into two components - reading and writing.

* Reading
    * Right now, in order to issue commands to a machine or bot interactively, it's necessary to actually visit it.
        * Users could instead issue commands via chat and using a prefix to their message
* Writing
    * Right now, in order to check the state of a machine or bot in-game, it's necessary to either visit it directly or else read the SMAPI console log.
        * The machine or bot could instead be programmed to shout state into chat for things that actually matter to the player
* Both
    * Some useful utilities only require access to arbitrary code execution and a text interface, and could be written using Farmtronics instead of a full blown Stardew Valley Mod
        * Dice rolling
        * Information services about the game state
        * and so on

Possible Implementation
---------------------------
As far as under the hood, I don't know much about Stardew Valley modding, sorry.

As far as a few key ideas and points, however, here:
*  Write: The bot or computer, when speaking, should probably use its name as a prefix, just like players do.
*  Write: It may be prudent to provide a mod config option to let players deny bots and computers the ability to run console commands, to future proof against potentially naïve or malicious behavior in the community or around it.
* Read: It may be best to maintain some variation on a global queue for log messages, as opposed to forcing players to specifically catch each message themselves when it first comes in.
    * Limiting the size of this would be wise for various reasons - not the least of which, it shouldn't eat up RAM for players who don't make use of it
    * Message numbering and throwaway when the queue exceeds a certain size would probably be the best utilities to let players see if they potentially missed a message.

Environment
--------------
* Version used:
    * Farmtronics 1.1.0
* Host operating system:
    * Windows 10 Home x64

**Comment by greysondn** [comment]
I would say part of my intention is to get the player away from having to check a computer/bot for status updates entirely. Otherwise "right on!"

**Comment by JoeStrout** [comment]
Implemented for the next release.  New method `world.chat` takes a string argument and adds it to the chat (along with the bot name, or "Home Computer").  And new method `world.chatMessages` returns a list of the last 10 or so chat messages.
