### ISSUE TITLE
Feature Request: Support Multiplayer sessions

### ISSUE THREAD

**Issue by greysondn** [JoeStrout/Farmtronics#20]
This request is very label-on-the-tin type.

JoeStrout has repeatedly stated he doesn't support multiplayer at the present time. This is just an issue directly requesting such support.

I recognize the amount of work that would take and the fact that even if not denied, this one might take quite some time.

Potentially related issue: #4 

Detailed Description
----------------------
The game features two types of multiplayer sessions - split-screen and networked.

What I'm proposing is that Farmtronics as a whole should be updated to support working reliably in both of them.

Usecase or Problem Being Solved
-------------------------------------
Farmtronics in multiplayer, man!

Possible Implementation
---------------------------
No bright ideas, sorry.

I realize this is hard and am prepared to wait quite some time. I just wanted to be sure the request was filed in the official issue log.

Environment
--------------
* Version used:
    * Farmtronics 1.1.0
* Host operating system:
    * Windows 10 Home x64

**Comment by JoeStrout** [comment]
Closing this issue as superseded by #32, which includes a more detailed proposal.
