### ISSUE TITLE
Bot inventory lost when you pick it up

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/Farmtronics#28]
Steps to reproduce:

1. Place seeds (or presumably anything else) into a bot.
2. Break the bot with a pickaxe and pick it up.
3. Put it back down again.
4. Open the bot and observe that the seeds (or whatever) are now gone.

(Reported by Discord user Mayer, not yet verified.)

**Comment by TSRBerry** [comment]
This is definitely fixed with #35, since we now don't allow the bot to be picked up if it contains items.

**Comment by JoeStrout** [comment]
This is believed fixed as of v1.0.7.  I suspect this user was using an older version of the mod.

**Comment by TSRBerry** [comment]
I see.
Even if this was an issue in the latest version with #41 the inventory was added to `modData`, so there should really be no way to make this happen again!
