### ISSUE TITLE
Harvesting with scythe

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/Farmtronics#31]
(Reported by discord user Phoenix_Firewind):

When a bot harvests using a scythe, it cuts the two crops to its left rather than the crop ahead of it.

1) Use a crop that requires a Scythe (Kale, Amaranth, Hay)
2) In order to see a harvest, the bot needs to be on the same line as the ready-to-be-harvested crop. In my picture, you can see the bot is x-1 from the north end of the field. Harvestable crop and bot need to be on the same  line
3) Bot should also have at least two crops that are ready to be harvested to it's left (ie, to the East when the bot is face South, to the West when the bot is facing North)
4) With the Scythe as the active tool, trigger bot.harvest
Before:
![image](https://user-images.githubusercontent.com/263365/182047336-76e3b69f-feb7-4f8c-bfef-65082a866954.png)
After:
![image](https://user-images.githubusercontent.com/263365/182047344-f5406d8a-c9b7-4b2c-9bd0-177f680d5215.png)

Expected behavior would be to take the crop in front of the bot (and possibly the ones to either side of that, given the typical action of a Scythe when used by a player).

**Comment by TSRBerry** [comment]
With #35 the bot harvests the tile in front of it, although it doesn't exactly mimic the behavior of the scythe, it should be better than before.

The reason for harvesting the crops to it's left is because the method responsible for performing this action (`HoeDirt.performUseAction()`) uses `Game1.player.lastClick` instead of `Game1.player.GetToolLocation()`.

**Comment by JoeStrout** [comment]
The crux of this issue is harvesting the wrong location.  With the changes in #35, the bot is harvesting the tile in front of it, so I'm going to close this issue.

Picking up loose items is kind of a separate issue that comes up in other contexts, as well.  I think we should tackle that as a separate task, and try to make it general enough to handle anything that might be lying around.
