### ISSUE TITLE
splitscreen issues

### ISSUE THREAD

**Issue by lg188** [JoeStrout/Farmtronics#4]
When playing the game locally, with split screen, there's a couple of things that seem to not be designed with this game mode in mind.

## Home computer
There's no way of getting out of this screen when the second player is connected with a controller. I had to kick that player and then they had to rejoin the game to get out of the window. 

## farmtronics robot
The robot sprite simply does not show up on the secondary screen. I haven't tried going into it with a secondary player, for I assume the aforementioned bug would occur, and therefore require a kick.

**Comment by JoeStrout** [comment]
Splitscreen is a type of multiplayer.  This mod does not yet support multiplayer.

But thank you for the report!  When we _do_ add multiplayer support, we will need your help making sure we don't miss any issues like this.
