### ISSUE TITLE
[Bug] saved files as "todo.ms" will overwrite "todo"-command

### ISSUE THREAD

**Issue by Hedrauta** [JoeStrout/Farmtronics#45]
saving a file as "todo.ms" in /usr will overwrite the original "toDo"-command

proof:
![STG (4)](https://user-images.githubusercontent.com/20142298/201779560-b8339df0-ac01-42fd-9a47-5a9fd449faea.gif)

**Comment by JoeStrout** [comment]
Well, it doesn't overwrite it so much as supersede it.  The `toDo` command does an `import "toDo"`.  And the `import` command always looks in the current directory, as well as /usr/lib, before looking in /sys/lib.

So, you've hacked your home computer in a way that breaks the toDo command (while in this directory), sure.  But I'm not certain that counts as a Farmtronics bug.  Being able to hack your computer is a big part of the point.  Maybe this is just a learning opportunity.

**Comment by Hedrauta** [comment]
🤔 watched into it.... 

well... i though, it would be able to only import the `/sys/todo.ms` instead of the `/usr`-one
well.... i'll close the issue then 😉
