### ISSUE TITLE
Stock "dir" command in /sys/startup.ms doesn't work with the /net directory

### ISSUE THREAD

**Issue by SinZ163** [JoeStrout/Farmtronics#47]
with `dir "/"` it prints `/usr` and `/sys` but not `/net`

and `dir` (or `dir "."`) when in the `/net` directory, it will print `Invalid path` when it is possible to read files in the folder and write files into the folder.

![image](https://user-images.githubusercontent.com/767456/212471869-444b3dbb-0635-4258-9228-bb3bc864f262.png)

**Comment by JoeStrout** [comment]
Good catch!  We'll get this fixed ASAP.
