### ISSUE TITLE
Console Mojibake on localized Games

### ISSUE THREAD

**Issue by tiansh** [JoeStrout/Farmtronics#7]
Bot returns localized values. But the console render CJK characters as square of question marks.

![Screenshot of mojibake](https://user-images.githubusercontent.com/6500326/151991366-0288187f-7201-405c-94ed-0ad7a4f6c276.png)

Typically, CJK Characters are rendered 2 letters width on console. The behavior could be tricky if try to support it. But maybe mod can include more un-localized information to the return value of API's so programs don't need to rely on these fields to work.

**Comment by JoeStrout** [comment]
The unlocalized strings your code should rely on are "type" and "name".  It's only "displayName" and "description" which are the localized strings, and you're right, the console can't display those if they are outside the Latin character set.

**Comment by tiansh** [comment]
Maybe the item `category` can be changed to an integer?

```csharp
result["category"] = new ValNumber(item.Category);
result["categoryName"] = new ValString(item.getCategoryName());
```
